
import java.awt.Toolkit;
import java.awt.event.KeyEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ManuelC
 */
public class App34 extends javax.swing.JFrame {

    Calculos34 calculo1 = new Calculos34();
    
    public App34() {
        initComponents();
    }
           public void validarCheck(){
                   
          if(checkPrincipal.isSelected()==true){
          txtCamaraPrincipal.setEnabled(true);
          checkSecundaria.setEnabled(true);
          checkFlash.setEnabled(true);

          }else if(checkPrincipal.isSelected()==false){
          txtCamaraPrincipal.setEnabled(false);
          checkSecundaria.setEnabled(false);
          }
          
            if(checkSecundaria.isSelected()){
          txtCamaraSecundaria.setEnabled(true);
          }else if(checkSecundaria.isSelected()==false){
          txtCamaraSecundaria.setEnabled(false);
          }
          
          
          }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbmMarca = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        checkPrincipal = new javax.swing.JCheckBox();
        checkSecundaria = new javax.swing.JCheckBox();
        checkFlash = new javax.swing.JCheckBox();
        txtCamaraPrincipal = new javax.swing.JTextField();
        txtCamaraSecundaria = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTextArea = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtCpu = new javax.swing.JTextField();
        txtPantalla = new javax.swing.JTextField();
        txtRam = new javax.swing.JTextField();
        txtBateria = new javax.swing.JTextField();
        txtGarantia = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        JLabelPuntaje = new javax.swing.JLabel();
        JLabelRespuesta = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Puntaje de Móviles");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dotum", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CPU número nucleos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dotum", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tamaño de pantalla");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 118, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dotum", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RAM");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 149, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dotum", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bateria ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dotum", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 235, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dotum", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tiempo de garantía");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 209, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dotum", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Marca");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 261, -1, -1));

        cbmMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alcatel", "Apple", "Huawei", "Lenovo", "LG", "Nexus", "Pixie", "Samsung", "Sony ", "Otra", " " }));
        getContentPane().add(cbmMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 261, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dotum", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cámaras");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 302, -1, -1));

        checkPrincipal.setFont(new java.awt.Font("Dotum", 0, 11)); // NOI18N
        checkPrincipal.setText("Principal");
        checkPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(checkPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 299, -1, -1));

        checkSecundaria.setFont(new java.awt.Font("Dotum", 0, 11)); // NOI18N
        checkSecundaria.setText("Secundaria");
        checkSecundaria.setEnabled(false);
        checkSecundaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSecundariaActionPerformed(evt);
            }
        });
        getContentPane().add(checkSecundaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 299, -1, -1));

        checkFlash.setFont(new java.awt.Font("Dotum", 0, 11)); // NOI18N
        checkFlash.setText("Flash");
        checkFlash.setEnabled(false);
        checkFlash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFlashActionPerformed(evt);
            }
        });
        getContentPane().add(checkFlash, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 299, -1, -1));

        txtCamaraPrincipal.setFont(new java.awt.Font("Dotum", 0, 11)); // NOI18N
        txtCamaraPrincipal.setEnabled(false);
        txtCamaraPrincipal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCamaraPrincipalKeyTyped(evt);
            }
        });
        getContentPane().add(txtCamaraPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 331, 64, -1));

        txtCamaraSecundaria.setFont(new java.awt.Font("Dotum", 0, 11)); // NOI18N
        txtCamaraSecundaria.setEnabled(false);
        getContentPane().add(txtCamaraSecundaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 331, 64, -1));

        btnCalcular.setFont(new java.awt.Font("Dotum", 0, 12)); // NOI18N
        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 329, -1, -1));

        JTextArea.setColumns(20);
        JTextArea.setRows(5);
        jScrollPane1.setViewportView(JTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 370, 233, 115));

        jLabel10.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Puntaje Obtenido");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 370, -1, -1));

        btnAtras.setFont(new java.awt.Font("Dotum", 0, 12)); // NOI18N
        btnAtras.setText("ATRÁS");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 496, -1, -1));

        btnLimpiar.setFont(new java.awt.Font("Dotum", 0, 12)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, -1, -1));

        txtCpu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCpuKeyTyped(evt);
            }
        });
        getContentPane().add(txtCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 90, 79, -1));

        txtPantalla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPantallaKeyTyped(evt);
            }
        });
        getContentPane().add(txtPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 116, 79, -1));

        txtRam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRamKeyTyped(evt);
            }
        });
        getContentPane().add(txtRam, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 147, 79, -1));

        txtBateria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBateriaKeyTyped(evt);
            }
        });
        getContentPane().add(txtBateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 178, 79, -1));

        txtGarantia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGarantiaKeyTyped(evt);
            }
        });
        getContentPane().add(txtGarantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 204, 79, -1));

        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 230, 79, -1));

        JLabelPuntaje.setFont(new java.awt.Font("Dotum", 1, 24)); // NOI18N
        JLabelPuntaje.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(JLabelPuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 394, 41, 37));

        JLabelRespuesta.setFont(new java.awt.Font("Dotum", 2, 12)); // NOI18N
        JLabelRespuesta.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(JLabelRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 120, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/12ad44f695d5bb9b83c32395534feef0.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPrincipalActionPerformed
        // TODO add your handling code here:}
        validarCheck();
    }//GEN-LAST:event_checkPrincipalActionPerformed

    private void checkSecundariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSecundariaActionPerformed
        // TODO add your handling code here:
        validarCheck();
    }//GEN-LAST:event_checkSecundariaActionPerformed

    private void checkFlashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFlashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkFlashActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed

        // TODO add your handling code here:
        
        Principal principal=new Principal();
       this.dispose();
       principal.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        
        JLabelPuntaje.setText("");
        JLabelRespuesta.setText("");
        txtBateria.setText("");
                txtCamaraPrincipal.setText("");
                txtCamaraSecundaria.setText("");
                                txtCpu.setText("");
                                                txtGarantia.setText("");
                                                                txtPantalla.setText("");
                                                                                txtPrecio.setText("");
                                                                                                txtRam.setText("");
                                                                                                
                                                                                                cbmMarca.setSelectedIndex(0);
                                                                                                checkPrincipal.isSelected();
                                                                                                checkSecundaria.isSelected();
JTextArea.setText("");




    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
    
       calculo1.setBateria(Integer.parseInt(txtBateria.getText()));
       calculo1.setCpu(Integer.parseInt(txtCpu.getText()));
       calculo1.setGarantia(Integer.parseInt(txtGarantia.getText()));
       calculo1.setPrecio(Integer.parseInt(txtPrecio.getText()));
       calculo1.setTamañoPantalla(Double.parseDouble(txtPantalla.getText()));
       calculo1.setRam(Double.parseDouble(txtRam.getText()));
       
       int opcionElegida = cbmMarca.getSelectedIndex();
       
       if (opcionElegida==0){
       calculo1.setMarca("Alcatel");
       }else if (opcionElegida==1){
       calculo1.setMarca("Apple");
       }else if (opcionElegida==2){
       calculo1.setMarca("Huawei");
       }else if (opcionElegida==3){
       calculo1.setMarca("Lenovo");
       }else if (opcionElegida==4){
       calculo1.setMarca("LG");
       }else if (opcionElegida==5){
       calculo1.setMarca("Nexus");
       }else if (opcionElegida==6){
       calculo1.setMarca("Pixie");
       }else if (opcionElegida==7){
       calculo1.setMarca("Samsung");
       }else if (opcionElegida==8){
       calculo1.setMarca("Sony");
       }else if (opcionElegida==9){
       calculo1.setMarca("Otra");
       }
       
       if (checkPrincipal.isSelected()==false){
              calculo1.setCamaraPrincipal(Double.parseDouble("No"));
             calculo1.setCamaraSecundaria(Double.parseDouble("No"));
             calculo1.setTieneFlash(false);

       }else {
       calculo1.setCamaraPrincipal(Double.parseDouble(txtCamaraPrincipal.getText()));
       calculo1.setCamaraSecundaria(Double.parseDouble(txtCamaraSecundaria.getText()));
       if(checkFlash.isSelected()==true){
       calculo1.setTieneFlash(true);

       }else if (checkFlash.isSelected()==false){
       calculo1.setTieneFlash(false);
           
       }
       
        if(checkPrincipal.isSelected()==true){
           calculo1.setTienePrincipal(true);
          }else if(checkPrincipal.isSelected()==false){
           calculo1.setTienePrincipal(false);
          
          }
       
       if(checkSecundaria.isSelected()==true){
           calculo1.setTieneSecundaria(true);
          }else if(checkSecundaria.isSelected()==false){
           calculo1.setTieneSecundaria(false);
          
          }
       
       }
       
       
       
        JTextArea.setText(calculo1.mostrar());
        
        calculo1.BateriaPantalla();
        calculo1.Cpu();
        calculo1.Ram();
        calculo1.garantia();
        calculo1.rangoPrecio();
        calculo1.refMarca();
        calculo1.pixelaje();
        JLabelPuntaje.setText(calculo1.mostrarPuntaje());
        JLabelRespuesta.setText(calculo1.Accion());
    }//GEN-LAST:event_btnCalcularActionPerformed

    
    
    
    
    
    
    
    
    private void txtCpuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpuKeyTyped
      char c=evt.getKeyChar();
        
        if(txtCpu.getText().length()<2 && Character.isLetter(c) ){
        evt.consume();
        Toolkit.getDefaultToolkit().beep();
        }else{
            int var=Integer.parseInt(""+c);
            if(txtCpu.getText().isEmpty()){
                if(var<=0){
                 evt.consume();
                 Toolkit.getDefaultToolkit().beep();
                }
            }else{
             int txt=(Integer.parseInt(txtCpu.getText()))*10;
                if((txt+var)>12){
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
                }
            }
        
       
     }        
    }//GEN-LAST:event_txtCpuKeyTyped

    private void txtPantallaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPantallaKeyTyped
        // TODO add your handling code here
        
        char c = evt.getKeyChar();
if (((c < '0') || (c > '9')) 
&& (c != '.') || (txtPantalla.getText().length()>2)) {
evt.consume();
}
if (c == '.' && txtPantalla.getText().contains(".")) {
evt.consume();
}   

    }//GEN-LAST:event_txtPantallaKeyTyped

    private void txtRamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRamKeyTyped
       char c = evt.getKeyChar();
if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)
&& (c != '.') || (txtRam.getText().length()>2)) {
evt.consume();
}
if (c == '.' && txtRam.getText().contains(".")) {
evt.consume();
} 


        // TODO add your handling code here:
    }//GEN-LAST:event_txtRamKeyTyped

    private void txtGarantiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGarantiaKeyTyped
char c=evt.getKeyChar();
        
        if(txtGarantia.getText().length()<2 && Character.isLetter(c)){
        evt.consume();
        Toolkit.getDefaultToolkit().beep();
        }else{
            int var=Integer.parseInt(""+c);
            if(txtGarantia.getText().isEmpty()){
                if(var<=0){
                 evt.consume();
                 Toolkit.getDefaultToolkit().beep();
                }
            }else{
             int txt=(Integer.parseInt(txtGarantia.getText()))*10;
                if((txt+var)>24){
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
                }
            }
        
       
     }                // TODO add your handling code here:
    }//GEN-LAST:event_txtGarantiaKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped

            char c = evt.getKeyChar();
if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)
&& (c != '.') || (txtPrecio.getText().length()>5)) {
evt.consume();
}
if (c == '.' && txtPrecio.getText().contains(".")) {
evt.consume();
}  
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtCamaraPrincipalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamaraPrincipalKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)
&& (c != '.') || (txtPantalla.getText().length()>3)) {
evt.consume();
}
if (c == '.' && txtPantalla.getText().contains(".")) {
evt.consume();
}  
    }//GEN-LAST:event_txtCamaraPrincipalKeyTyped

    private void txtBateriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBateriaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBateriaKeyTyped
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App34.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App34.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App34.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App34.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App34().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelPuntaje;
    private javax.swing.JLabel JLabelRespuesta;
    private javax.swing.JTextArea JTextArea;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbmMarca;
    private javax.swing.JCheckBox checkFlash;
    private javax.swing.JCheckBox checkPrincipal;
    private javax.swing.JCheckBox checkSecundaria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBateria;
    private javax.swing.JTextField txtCamaraPrincipal;
    private javax.swing.JTextField txtCamaraSecundaria;
    private javax.swing.JTextField txtCpu;
    private javax.swing.JTextField txtGarantia;
    private javax.swing.JTextField txtPantalla;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtRam;
    // End of variables declaration//GEN-END:variables
}
