/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ManuelC
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButtonApp2 = new javax.swing.JButton();
        jButtonApp3 = new javax.swing.JButton();
        jButtonApp1 = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jButton3.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jButton3.setText("APP GUIA 1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonApp2.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jButtonApp2.setText("APP 2");
        jButtonApp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApp2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, 150));

        jButtonApp3.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jButtonApp3.setText("APP 3");
        jButtonApp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApp3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 190, 90));

        jButtonApp1.setBackground(new java.awt.Color(204, 204, 255));
        jButtonApp1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jButtonApp1.setText("APP 1");
        jButtonApp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApp1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 190, 50));

        jButtonSalir.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¿Qué vamos a hacer?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/12ad44f695d5bb9b83c32395534feef0.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonApp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApp2ActionPerformed
        Menú  app2=new Menú();
        this.dispose();
        app2.setVisible(true);
    }//GEN-LAST:event_jButtonApp2ActionPerformed

    private void jButtonApp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApp3ActionPerformed
    
        App34 app34=new App34();
        this.dispose();
        app34.setVisible(true);
        


        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonApp3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonApp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApp1ActionPerformed
        NewJFrame app1=new NewJFrame();
        this.dispose();
        app1.setVisible(true);
    }//GEN-LAST:event_jButtonApp1ActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        Login ventana1=new Login();
        this.dispose();
        ventana1.setVisible(true);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonApp1;
    private javax.swing.JButton jButtonApp2;
    private javax.swing.JButton jButtonApp3;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
